### ISSUE TITLE
Issue with frequency information in single IP on command line

### ISSUE THREAD

**Issue by chapinb** [chapinb/chickadee#28]
Partial error:

```
$ chickadee -p -s 1.1.1.1
[...]
2020-01-14 23:15:00,303 chickadee.py INFO chickadee resolve:181 - Resolved IPs
Traceback (most recent call last):
  File "/usr/local/bin/chickadee", line 8, in <module>
    sys.exit(entry())
  File "/usr/local/lib/python3.7/site-packages/libchickadee/chickadee.py", line 360, in entry
    res = chickadee.run(x)
  File "/usr/local/lib/python3.7/site-packages/libchickadee/chickadee.py", line 85, in run
    results = self.resolve(result_dict)
  File "/usr/local/lib/python3.7/site-packages/libchickadee/chickadee.py", line 187, in resolve
    query = str(result.get('query', ''))
AttributeError: 'list' object has no attribute 'get'
```

**Comment by chapinb** [comment]
Closed by #30
