### ISSUE TITLE
Can't install via pip on macOS?

### ISSUE THREAD

**Issue by luckman212** [chapinb/chickadee#80]
Until https://github.com/chapinb/chickadee/issues/32 is landed in Homebrew, I'm trying to do a manual install on macOS 13.4, but hitting a wall 😢 🐤

Here is what I'm trying... I tried to follow the [Installation docs](https://chapinb.com/chickadee/index.html#installation) as closely as possible

### Versions

```
macOS = 13.4
python3 = 3.11.3
pip = 23.1.2
virtualenv = 20.23.0
```

### Commands

> _**N.B.** on my system `WORKON_HOME=~/.virtualenvs`_

```shell
cd $WORKON_HOME
git clone https://github.com/chapinb/chickadee.git
cd chickadee/
virtualenv -p python3 venv3
source venv3/bin/activate
pip install .
```

### The error output
```
Processing /Users/luke/.virtualenvs/chickadee
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "/Users/luke/.virtualenvs/chickadee/venv3/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/luke/.virtualenvs/chickadee/venv3/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/luke/.virtualenvs/chickadee/venv3/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/n1/kwxhk1g96vl592mftk5lwntc0000gn/T/pip-build-env-tii_4j18/overlay/lib/python3.11/site-packages/poetry/core/masonry/api.py", line 42, in prepare_metadata_for_build_wheel
          builder = WheelBuilder(poetry)
                    ^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/n1/kwxhk1g96vl592mftk5lwntc0000gn/T/pip-build-env-tii_4j18/overlay/lib/python3.11/site-packages/poetry/core/masonry/builders/wheel.py", line 60, in __init__
          super().__init__(poetry, executable=executable)
        File "/private/var/folders/n1/kwxhk1g96vl592mftk5lwntc0000gn/T/pip-build-env-tii_4j18/overlay/lib/python3.11/site-packages/poetry/core/masonry/builders/builder.py", line 85, in __init__
          self._module = Module(
                         ^^^^^^^
        File "/private/var/folders/n1/kwxhk1g96vl592mftk5lwntc0000gn/T/pip-build-env-tii_4j18/overlay/lib/python3.11/site-packages/poetry/core/masonry/utils/module.py", line 69, in __init__
          raise ModuleOrPackageNotFound(
      poetry.core.masonry.utils.module.ModuleOrPackageNotFound: No file/folder found for package chickadee
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by chapinb** [comment]
Thanks for the report! I was able to reproduce this error and will work on a fix.

**Comment by chapinb** [comment]
In the meantime, if you'd like to use the CLI tool you can use `pip install chickadee` to install the package within your environment.

**Comment by luckman212** [comment]
Thanks. I appreciate the help. I made a new venv and installed with `pip install chickadee` as you described.

But, it won't run, there's a numpy error

```
$ chickadee -h
Traceback (most recent call last):
  File "/Users/luke/.virtualenvs/bin/chickadee", line 5, in <module>
    from libchickadee.chickadee import entry
  File "/Users/luke/.virtualenvs/chickadee/lib/python3.11/site-packages/libchickadee/chickadee.py", line 169, in <module>
    from libchickadee.parsers.xlsx import XLSXParser
  File "/Users/luke/.virtualenvs/chickadee/lib/python3.11/site-packages/libchickadee/parsers/xlsx.py", line 10, in <module>
    from openpyxl import load_workbook
  File "/Users/luke/.virtualenvs/chickadee/lib/python3.11/site-packages/openpyxl/__init__.py", line 4, in <module>
    from openpyxl.compat.numbers import NUMPY, PANDAS
  File "/Users/luke/.virtualenvs/chickadee/lib/python3.11/site-packages/openpyxl/compat/__init__.py", line 5, in <module>
    from .strings import (
  File "/Users/luke/.virtualenvs/chickadee/lib/python3.11/site-packages/openpyxl/compat/strings.py", line 10, in <module>
    from .numbers import NUMERIC_TYPES
  File "/Users/luke/.virtualenvs/chickadee/lib/python3.11/site-packages/openpyxl/compat/numbers.py", line 49, in <module>
    numpy.float,
    ^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'cfloat'?
```

**Comment by luckman212** [comment]
Thanks - that worked! 🚀 
Here are the commands I used, for anyone's benefit.

```
cd $WORKON_HOME
git clone --depth 1 --branch use-poetry https://github.com/chapinb/chickadee.git
cd chickadee/
virtualenv -p python3 venv3
source venv3/bin/activate
pip install .
deactivate
$WORKON_HOME/chickadee/venv3/bin/chickadee 1.1.1.1 | jq
```

The only thing I noticed is this version prints out a debug `INFO` message at the start of every operation. Is there a way to disable that (besides adding `2>/dev/null` to the command) ?

**Comment by chapinb** [comment]
Ah thanks for the call out on the INFO message, I will drop that.

**Comment by luckman212** [comment]
@chapinb Yes that branch is working for me!
